package model;
// Generated Dec 29, 2018 5:07:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Cotisation generated by hbm2java
 */
@Entity
@Table(name = "cotisation")
public class Cotisation implements java.io.Serializable {

	private Integer idCotisation;
	private UserCoproprietaire userCoproprietaire;
	private Integer montantCotisation;
	private CotisationAnnuel cotisationAnnuel;
	private CotisationMensuel cotisationMensuel;

	public Cotisation() {
	}

	public Cotisation(UserCoproprietaire userCoproprietaire) {
		this.userCoproprietaire = userCoproprietaire;
	}

	public Cotisation(UserCoproprietaire userCoproprietaire, Integer montantCotisation,
			CotisationAnnuel cotisationAnnuel, CotisationMensuel cotisationMensuel) {
		this.userCoproprietaire = userCoproprietaire;
		this.montantCotisation = montantCotisation;
		this.cotisationAnnuel = cotisationAnnuel;
		this.cotisationMensuel = cotisationMensuel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Cotisation", unique = true, nullable = false)
	public Integer getIdCotisation() {
		return this.idCotisation;
	}

	public void setIdCotisation(Integer idCotisation) {
		this.idCotisation = idCotisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_User", nullable = false)
	public UserCoproprietaire getUserCoproprietaire() {
		return this.userCoproprietaire;
	}

	public void setUserCoproprietaire(UserCoproprietaire userCoproprietaire) {
		this.userCoproprietaire = userCoproprietaire;
	}

	@Column(name = "montant_Cotisation", precision = 8, scale = 0)
	public Integer getMontantCotisation() {
		return this.montantCotisation;
	}

	public void setMontantCotisation(Integer montantCotisation) {
		this.montantCotisation = montantCotisation;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "cotisation")
	public CotisationAnnuel getCotisationAnnuel() {
		return this.cotisationAnnuel;
	}

	public void setCotisationAnnuel(CotisationAnnuel cotisationAnnuel) {
		this.cotisationAnnuel = cotisationAnnuel;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "cotisation")
	public CotisationMensuel getCotisationMensuel() {
		return this.cotisationMensuel;
	}

	public void setCotisationMensuel(CotisationMensuel cotisationMensuel) {
		this.cotisationMensuel = cotisationMensuel;
	}

}
