package model;
// Generated Dec 29, 2018 5:07:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FrsEntreprise generated by hbm2java
 */
@Entity
@Table(name = "frs_entreprise")
public class FrsEntreprise implements java.io.Serializable {

	private int idFournisseurs;
	private Fournisseurs fournisseurs;

	public FrsEntreprise() {
	}

	public FrsEntreprise(Fournisseurs fournisseurs) {
		this.fournisseurs = fournisseurs;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "fournisseurs"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_Fournisseurs", unique = true, nullable = false)
	public int getIdFournisseurs() {
		return this.idFournisseurs;
	}

	public void setIdFournisseurs(int idFournisseurs) {
		this.idFournisseurs = idFournisseurs;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Fournisseurs getFournisseurs() {
		return this.fournisseurs;
	}

	public void setFournisseurs(Fournisseurs fournisseurs) {
		this.fournisseurs = fournisseurs;
	}

}
