package model;
// Generated Dec 29, 2018 5:07:18 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification")
public class Notification implements java.io.Serializable {

	private Integer idNotification;
	private Date dateNotification;
	private String textNotification;
	private Set<NotificationUser> notificationUsers = new HashSet<NotificationUser>(0);

	public Notification() {
	}

	public Notification(Date dateNotification, String textNotification, Set<NotificationUser> notificationUsers) {
		this.dateNotification = dateNotification;
		this.textNotification = textNotification;
		this.notificationUsers = notificationUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Notification", unique = true, nullable = false)
	public Integer getIdNotification() {
		return this.idNotification;
	}

	public void setIdNotification(Integer idNotification) {
		this.idNotification = idNotification;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_Notification", length = 19)
	public Date getDateNotification() {
		return this.dateNotification;
	}

	public void setDateNotification(Date dateNotification) {
		this.dateNotification = dateNotification;
	}

	@Column(name = "text_Notification", length = 254)
	public String getTextNotification() {
		return this.textNotification;
	}

	public void setTextNotification(String textNotification) {
		this.textNotification = textNotification;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notification")
	public Set<NotificationUser> getNotificationUsers() {
		return this.notificationUsers;
	}

	public void setNotificationUsers(Set<NotificationUser> notificationUsers) {
		this.notificationUsers = notificationUsers;
	}

}
