package model;
// Generated Dec 29, 2018 5:07:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProprieteFrsId generated by hbm2java
 */
@Embeddable
public class ProprieteFrsId implements java.io.Serializable {

	private int idPropriete;
	private int idFournisseurs;

	public ProprieteFrsId() {
	}

	public ProprieteFrsId(int idPropriete, int idFournisseurs) {
		this.idPropriete = idPropriete;
		this.idFournisseurs = idFournisseurs;
	}

	@Column(name = "id_Propriete", nullable = false)
	public int getIdPropriete() {
		return this.idPropriete;
	}

	public void setIdPropriete(int idPropriete) {
		this.idPropriete = idPropriete;
	}

	@Column(name = "id_Fournisseurs", nullable = false)
	public int getIdFournisseurs() {
		return this.idFournisseurs;
	}

	public void setIdFournisseurs(int idFournisseurs) {
		this.idFournisseurs = idFournisseurs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProprieteFrsId))
			return false;
		ProprieteFrsId castOther = (ProprieteFrsId) other;

		return (this.getIdPropriete() == castOther.getIdPropriete())
				&& (this.getIdFournisseurs() == castOther.getIdFournisseurs());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPropriete();
		result = 37 * result + this.getIdFournisseurs();
		return result;
	}

}
