package model;
// Generated Dec 29, 2018 5:07:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SyndicProprieteId generated by hbm2java
 */
@Embeddable
public class SyndicProprieteId implements java.io.Serializable {

	private int idUser;
	private int idPropriete;

	public SyndicProprieteId() {
	}

	public SyndicProprieteId(int idUser, int idPropriete) {
		this.idUser = idUser;
		this.idPropriete = idPropriete;
	}

	@Column(name = "id_User", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "id_Propriete", nullable = false)
	public int getIdPropriete() {
		return this.idPropriete;
	}

	public void setIdPropriete(int idPropriete) {
		this.idPropriete = idPropriete;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SyndicProprieteId))
			return false;
		SyndicProprieteId castOther = (SyndicProprieteId) other;

		return (this.getIdUser() == castOther.getIdUser()) && (this.getIdPropriete() == castOther.getIdPropriete());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdPropriete();
		return result;
	}

}
