package model;
// Generated Dec 29, 2018 5:07:18 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ville generated by hbm2java
 */
@Entity
@Table(name = "ville")
public class Ville implements java.io.Serializable {

	private Integer idVille;
	private String nomVille;
	private Set<Propriete> proprietes = new HashSet<Propriete>(0);

	public Ville() {
	}

	public Ville(String nomVille, Set<Propriete> proprietes) {
		this.nomVille = nomVille;
		this.proprietes = proprietes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Ville", unique = true, nullable = false)
	public Integer getIdVille() {
		return this.idVille;
	}

	public void setIdVille(Integer idVille) {
		this.idVille = idVille;
	}

	@Column(name = "nom_Ville", length = 254)
	public String getNomVille() {
		return this.nomVille;
	}

	public void setNomVille(String nomVille) {
		this.nomVille = nomVille;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ville")
	public Set<Propriete> getProprietes() {
		return this.proprietes;
	}

	public void setProprietes(Set<Propriete> proprietes) {
		this.proprietes = proprietes;
	}
	public boolean hasNomVille() {
		return nomVille != null && !"".equals(nomVille.trim());
	}

}
