// default package
// Generated Dec 21, 2018 3:25:04 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assemble generated by hbm2java
 */
@Entity
@Table(name = "assemble", catalog = "copropriete")
public class Assemble implements java.io.Serializable {

	private Integer idAssemble;
	private Propriete propriete;
	private Date dateAssemble;
	private Integer dureeAssemble;
	private Set<Rapport> rapports = new HashSet<Rapport>(0);
	private Set<VoteCopropProp> voteCopropProps = new HashSet<VoteCopropProp>(0);

	public Assemble() {
	}

	public Assemble(Propriete propriete) {
		this.propriete = propriete;
	}

	public Assemble(Propriete propriete, Date dateAssemble, Integer dureeAssemble, Set<Rapport> rapports,
			Set<VoteCopropProp> voteCopropProps) {
		this.propriete = propriete;
		this.dateAssemble = dateAssemble;
		this.dureeAssemble = dureeAssemble;
		this.rapports = rapports;
		this.voteCopropProps = voteCopropProps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Assemble", unique = true, nullable = false)
	public Integer getIdAssemble() {
		return this.idAssemble;
	}

	public void setIdAssemble(Integer idAssemble) {
		this.idAssemble = idAssemble;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Propriete", nullable = false)
	public Propriete getPropriete() {
		return this.propriete;
	}

	public void setPropriete(Propriete propriete) {
		this.propriete = propriete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_Assemble", length = 19)
	public Date getDateAssemble() {
		return this.dateAssemble;
	}

	public void setDateAssemble(Date dateAssemble) {
		this.dateAssemble = dateAssemble;
	}

	@Column(name = "duree_Assemble")
	public Integer getDureeAssemble() {
		return this.dureeAssemble;
	}

	public void setDureeAssemble(Integer dureeAssemble) {
		this.dureeAssemble = dureeAssemble;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assemble")
	public Set<Rapport> getRapports() {
		return this.rapports;
	}

	public void setRapports(Set<Rapport> rapports) {
		this.rapports = rapports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assemble")
	public Set<VoteCopropProp> getVoteCopropProps() {
		return this.voteCopropProps;
	}

	public void setVoteCopropProps(Set<VoteCopropProp> voteCopropProps) {
		this.voteCopropProps = voteCopropProps;
	}

}
