// default package
// Generated Dec 21, 2018 3:25:04 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LocationBien generated by hbm2java
 */
@Entity
@Table(name = "location_bien", catalog = "copropriete")
public class LocationBien implements java.io.Serializable {

	private LocationBienId id;
	private BienCommun bienCommun;
	private Location location;
	private Date dateDLocBien;
	private Date dateFLocBien;
	private Integer montantLocation;

	public LocationBien() {
	}

	public LocationBien(LocationBienId id, BienCommun bienCommun, Location location) {
		this.id = id;
		this.bienCommun = bienCommun;
		this.location = location;
	}

	public LocationBien(LocationBienId id, BienCommun bienCommun, Location location, Date dateDLocBien,
			Date dateFLocBien, Integer montantLocation) {
		this.id = id;
		this.bienCommun = bienCommun;
		this.location = location;
		this.dateDLocBien = dateDLocBien;
		this.dateFLocBien = dateFLocBien;
		this.montantLocation = montantLocation;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idBien", column = @Column(name = "id_Bien", nullable = false)),
			@AttributeOverride(name = "idLocation", column = @Column(name = "id_Location", nullable = false)) })
	public LocationBienId getId() {
		return this.id;
	}

	public void setId(LocationBienId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Bien", nullable = false, insertable = false, updatable = false)
	public BienCommun getBienCommun() {
		return this.bienCommun;
	}

	public void setBienCommun(BienCommun bienCommun) {
		this.bienCommun = bienCommun;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Location", nullable = false, insertable = false, updatable = false)
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateD_Loc_Bien", length = 19)
	public Date getDateDLocBien() {
		return this.dateDLocBien;
	}

	public void setDateDLocBien(Date dateDLocBien) {
		this.dateDLocBien = dateDLocBien;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateF_Loc_Bien", length = 19)
	public Date getDateFLocBien() {
		return this.dateFLocBien;
	}

	public void setDateFLocBien(Date dateFLocBien) {
		this.dateFLocBien = dateFLocBien;
	}

	@Column(name = "montant_Location", precision = 8, scale = 0)
	public Integer getMontantLocation() {
		return this.montantLocation;
	}

	public void setMontantLocation(Integer montantLocation) {
		this.montantLocation = montantLocation;
	}

}
