// default package
// Generated Dec 21, 2018 3:25:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocationBienId generated by hbm2java
 */
@Embeddable
public class LocationBienId implements java.io.Serializable {

	private int idBien;
	private int idLocation;

	public LocationBienId() {
	}

	public LocationBienId(int idBien, int idLocation) {
		this.idBien = idBien;
		this.idLocation = idLocation;
	}

	@Column(name = "id_Bien", nullable = false)
	public int getIdBien() {
		return this.idBien;
	}

	public void setIdBien(int idBien) {
		this.idBien = idBien;
	}

	@Column(name = "id_Location", nullable = false)
	public int getIdLocation() {
		return this.idLocation;
	}

	public void setIdLocation(int idLocation) {
		this.idLocation = idLocation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocationBienId))
			return false;
		LocationBienId castOther = (LocationBienId) other;

		return (this.getIdBien() == castOther.getIdBien()) && (this.getIdLocation() == castOther.getIdLocation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdBien();
		result = 37 * result + this.getIdLocation();
		return result;
	}

}
