// default package
// Generated Dec 21, 2018 3:25:04 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "copropriete")
public class Location implements java.io.Serializable {

	private Integer idLocation;
	private Set<LocationBien> locationBiens = new HashSet<LocationBien>(0);

	public Location() {
	}

	public Location(Set<LocationBien> locationBiens) {
		this.locationBiens = locationBiens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Location", unique = true, nullable = false)
	public Integer getIdLocation() {
		return this.idLocation;
	}

	public void setIdLocation(Integer idLocation) {
		this.idLocation = idLocation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<LocationBien> getLocationBiens() {
		return this.locationBiens;
	}

	public void setLocationBiens(Set<LocationBien> locationBiens) {
		this.locationBiens = locationBiens;
	}

}
