// default package
// Generated Dec 21, 2018 3:25:04 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProprieteFrs generated by hbm2java
 */
@Entity
@Table(name = "propriete_frs", catalog = "copropriete")
public class ProprieteFrs implements java.io.Serializable {

	private ProprieteFrsId id;
	private Fournisseurs fournisseurs;
	private Propriete propriete;
	private Date datePropFrs;
	private String objetFournisseur;

	public ProprieteFrs() {
	}

	public ProprieteFrs(ProprieteFrsId id, Fournisseurs fournisseurs, Propriete propriete) {
		this.id = id;
		this.fournisseurs = fournisseurs;
		this.propriete = propriete;
	}

	public ProprieteFrs(ProprieteFrsId id, Fournisseurs fournisseurs, Propriete propriete, Date datePropFrs,
			String objetFournisseur) {
		this.id = id;
		this.fournisseurs = fournisseurs;
		this.propriete = propriete;
		this.datePropFrs = datePropFrs;
		this.objetFournisseur = objetFournisseur;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPropriete", column = @Column(name = "id_Propriete", nullable = false)),
			@AttributeOverride(name = "idFournisseurs", column = @Column(name = "id_Fournisseurs", nullable = false)) })
	public ProprieteFrsId getId() {
		return this.id;
	}

	public void setId(ProprieteFrsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Fournisseurs", nullable = false, insertable = false, updatable = false)
	public Fournisseurs getFournisseurs() {
		return this.fournisseurs;
	}

	public void setFournisseurs(Fournisseurs fournisseurs) {
		this.fournisseurs = fournisseurs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Propriete", nullable = false, insertable = false, updatable = false)
	public Propriete getPropriete() {
		return this.propriete;
	}

	public void setPropriete(Propriete propriete) {
		this.propriete = propriete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_Prop_Frs", length = 19)
	public Date getDatePropFrs() {
		return this.datePropFrs;
	}

	public void setDatePropFrs(Date datePropFrs) {
		this.datePropFrs = datePropFrs;
	}

	@Column(name = "objet_Fournisseur", length = 254)
	public String getObjetFournisseur() {
		return this.objetFournisseur;
	}

	public void setObjetFournisseur(String objetFournisseur) {
		this.objetFournisseur = objetFournisseur;
	}

}
