// default package
// Generated Dec 21, 2018 3:25:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rapport generated by hbm2java
 */
@Entity
@Table(name = "rapport", catalog = "copropriete")
public class Rapport implements java.io.Serializable {

	private Integer idRapport;
	private Assemble assemble;
	private String textRapport;

	public Rapport() {
	}

	public Rapport(Assemble assemble) {
		this.assemble = assemble;
	}

	public Rapport(Assemble assemble, String textRapport) {
		this.assemble = assemble;
		this.textRapport = textRapport;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Rapport", unique = true, nullable = false)
	public Integer getIdRapport() {
		return this.idRapport;
	}

	public void setIdRapport(Integer idRapport) {
		this.idRapport = idRapport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Assemble", nullable = false)
	public Assemble getAssemble() {
		return this.assemble;
	}

	public void setAssemble(Assemble assemble) {
		this.assemble = assemble;
	}

	@Column(name = "text_Rapport", length = 254)
	public String getTextRapport() {
		return this.textRapport;
	}

	public void setTextRapport(String textRapport) {
		this.textRapport = textRapport;
	}

}
