// default package
// Generated Dec 21, 2018 3:25:04 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserSyndic generated by hbm2java
 */
@Entity
@Table(name = "user_syndic", catalog = "copropriete")
public class UserSyndic implements java.io.Serializable {

	private int idUser;
	private User user;
	private Set<SyndicPropriete> syndicProprietes = new HashSet<SyndicPropriete>(0);

	public UserSyndic() {
	}

	public UserSyndic(User user) {
		this.user = user;
	}

	public UserSyndic(User user, Set<SyndicPropriete> syndicProprietes) {
		this.user = user;
		this.syndicProprietes = syndicProprietes;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_User", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userSyndic")
	public Set<SyndicPropriete> getSyndicProprietes() {
		return this.syndicProprietes;
	}

	public void setSyndicProprietes(Set<SyndicPropriete> syndicProprietes) {
		this.syndicProprietes = syndicProprietes;
	}

}
